language: python
dist: xenial
cache: pip
services:
  - docker

# stage decl.
stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
os:
  - linux
env:
  global:
    - BACKEND_ETCD_ADDR=localhost:2379
    - BACKEND_NAMESPACE=local
python:
  - "3.6"
  - "3.7"

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
before_script:
  - mkdir -p /tmp/etcd
  - docker run -d -p 2379:2379 -p 2380:2380
     -v /tmp/etcd:/etcd-data
     --name backendai-etcd
     quay.io/coreos/etcd:v3.3.9
     /usr/local/bin/etcd
     --name backendai-etcd
     --data-dir /etcd-data
     --listen-client-urls http://0.0.0.0:2379
     --advertise-client-urls http://0.0.0.0:2379
     --listen-peer-urls http://0.0.0.0:2380
     --initial-advertise-peer-urls http://0.0.0.0:2380
     --initial-cluster backendai-etcd=http://0.0.0.0:2380
     --initial-cluster-token backendai-etcd-token
     --initial-cluster-state new
     --auto-compaction-retention 1
script:
  - python -m flake8 src tests
  - python -m pytest --cov=src -v
after_success:
  - codecov

# stage def.
jobs:
  include:
    - stage: deploy
      python: "3.6"
      install:
        - pip install -U pip setuptools
        - pip install -U -r requirements-build.txt
      before_script: skip
      script: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: "@token"
        password:
          secure: "jnSFUGoLVf3gwTtVybM47cMG9alR9Ocj9jL7lX+DavwiT2Ez0iD7/MIbP9Yj8EAjpab0uZl5lUfpLkNk7iKUAd0BR7SOj5b4PHITbZYubFCkqXFEr7zUQXNjrSSsz2HX1/7oe7QKcE0remxmUOWAsB1XWjhEVCWMRk1epZ5x4ZJlpt8EsrmXBUdAX+1xMtvIF4nMmA7r8wkY1iMvw1VHp9DGTMwYcM/qhpwf0ykksQ7V8zqH1qQk/35epcgJOgTINAWp9KCkyCh8pzyv8qSescpR1Jcr22mTdG/3o4PV16Pk0f4NdA4ELBO2hR+RA3/h7Ulc5Aw5TrZDBmCi3Peb+7l6lC2ifsb42wid4MhN2P78ki4W0GfZZzVZtLYKBEk1I2uEWzdydAYoXtMPCbVi/swGvf4wYMg1LMZuDKrQheRc1kIskAdP2cjfmozOZ5jR9R4IJieoW7iHTCANbdgJoPbxM7A9doZ4mTUOdIzMJgWv7Pz7NXpbMpLMBTZmWDh8roXadrmKt+Dwmzjqr6vsRUFWBsSH0zJ8haE2LEUTjb0mgYXMDAKewluyQ++NjtTHPpfB0UURsNYp8RLzMr+S/JXlWFlbHzc4O8hJ22+NRYRd5V7zEVLyDyAgUVAE8nTT1uK8UqU8T5ywqW4DybBEluX10Q13oM+IQnsDj9GdLM0="

notifications:
  webhooks:
    secure: "Gd9njovK7f0UBDDuwwwNUSIhaipvQQOjXWkPsNXZr04eO43PqElnOn2emjDEiXO78Ovu5GGyUk27fhmqy7JdYTHPVAAd98fVbmzFwPu3XKvDNSrylbrckqoKRejcN5rRsPSzMFOklhwC/NHKiBz+XD2OhfITAqrnSc5BXKnHgBfPxK5s662oj6pQl3Uvvp5RCsuU8ceHq7xg224Kdkx2If+0oyB/8xRqG4E6vCS55jnxGFCOjGkfNg1wP8v9c8a9R7KNtz4ErlxQ5hVzCE8l6pHUTvscehzu/7JJmxziKLuXJYOyUGOKJCaHcYPRoUiPo6N0WbW1snDHK0d6XNGz7BFS3DVfzBama6pB3h4uiM02k8I+lm13L2xXN0A9ger0pRvDEieUTnXEc/zEy9wPCkSbFKMSkbshEPHnFzvDNJIaQELIQ+zXmNdBSCki3848WKMh85REwRwxczHr+bgz8JILb5DSgDBSJu2G7mOWCM5dohDrH6UfLI6fG4Dl48dJpu8pEO86PxE7MJ/u+fgnEGjINaaudoM29TQ4ArXNLHcC2C40ONWh/nsmzktAz/WgVPSvLtyJGA4lSgRkzxSGNr8rG1OMM1jeE/kBu246P26di+AcYX3o1JjKQhI3U2ql9ht0npIRWxO31aWn1kY+GYyjPt9/QSBTwPY0PY0dkxQ="
