sudo: required

language: python
python:
  - "3.6"
cache: pip

services:
  - docker
  - rabbitmq

env:
  global:
    - SORNA_ETCD_ADDR=localhost:2379
    - SORNA_MQ_ADDR=localhost:5672
    - SORNA_MQ_LOGIN=guest
    - SORNA_MQ_PASS=guest
    - SORNA_NAMESPACE=local

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt

before_script:
  - mkdir -p /tmp/etcd
  - sudo rabbitmqctl add_vhost "$SORNA_NAMESPACE"
  - sudo rabbitmqctl set_permissions -p "$SORNA_NAMESPACE" "$SORNA_MQ_LOGIN" '.*' '.*' '.*'
  - docker run -d -p 2379:2379 -p 2380:2380
     -v /tmp/etcd:/etcd-data
     --name sorna-etcd
     quay.io/coreos/etcd:v3.1.8
     /usr/local/bin/etcd
     -name sorna-etcd
     -data-dir /etcd-data
     -listen-client-urls http://0.0.0.0:2379
     -advertise-client-urls http://0.0.0.0:2379
     -listen-peer-urls http://0.0.0.0:2380
     -initial-advertise-peer-urls http://0.0.0.0:2380
     -initial-cluster sorna-etcd=http://0.0.0.0:2380
     -initial-cluster-token sorna-etcd-token
     -initial-cluster-state new
     -auto-compaction-retention 1

script:
  - flake8 sorna tests
  - python -m pytest -m "not integration" --cov=sorna

after_success:
  - codecov

notifications:
  webhooks:
    secure: "Gd9njovK7f0UBDDuwwwNUSIhaipvQQOjXWkPsNXZr04eO43PqElnOn2emjDEiXO78Ovu5GGyUk27fhmqy7JdYTHPVAAd98fVbmzFwPu3XKvDNSrylbrckqoKRejcN5rRsPSzMFOklhwC/NHKiBz+XD2OhfITAqrnSc5BXKnHgBfPxK5s662oj6pQl3Uvvp5RCsuU8ceHq7xg224Kdkx2If+0oyB/8xRqG4E6vCS55jnxGFCOjGkfNg1wP8v9c8a9R7KNtz4ErlxQ5hVzCE8l6pHUTvscehzu/7JJmxziKLuXJYOyUGOKJCaHcYPRoUiPo6N0WbW1snDHK0d6XNGz7BFS3DVfzBama6pB3h4uiM02k8I+lm13L2xXN0A9ger0pRvDEieUTnXEc/zEy9wPCkSbFKMSkbshEPHnFzvDNJIaQELIQ+zXmNdBSCki3848WKMh85REwRwxczHr+bgz8JILb5DSgDBSJu2G7mOWCM5dohDrH6UfLI6fG4Dl48dJpu8pEO86PxE7MJ/u+fgnEGjINaaudoM29TQ4ArXNLHcC2C40ONWh/nsmzktAz/WgVPSvLtyJGA4lSgRkzxSGNr8rG1OMM1jeE/kBu246P26di+AcYX3o1JjKQhI3U2ql9ht0npIRWxO31aWn1kY+GYyjPt9/QSBTwPY0PY0dkxQ="
