language: python

cache: pip

services:
  - docker

python:
  - "3.6"

install:
  - pip install -U pip
  - pip install -U wheel setuptools
  - pip install -U -r requirements-dev.txt

env:
  global:
    - SORNA_ETCD_ADDR=localhost:2379
    - SORNA_MQ_ADDR=localhost:5672
    - SORNA_MQ_LOGIN=sorna
    - SORNA_MQ_PASS=develove
    - SORNA_NAMESPACE=local

before_script:
  - mkdir -p /tmp/etcd
  - docker run -d -p 2379:2379 -p 2380:2380
     -v /tmp/etcd:/etcd-data
     --name sorna-etcd
     quay.io/coreos/etcd:v3.1.8
     /usr/local/bin/etcd
     -name sorna-etcd
     -data-dir /etcd-data
     -listen-client-urls http://0.0.0.0:2379
     -advertise-client-urls http://0.0.0.0:2379
     -listen-peer-urls http://0.0.0.0:2380
     -initial-advertise-peer-urls http://0.0.0.0:2380
     -initial-cluster sorna-etcd=http://0.0.0.0:2380
     -initial-cluster-token sorna-etcd-token
     -initial-cluster-state new
     -auto-compaction-retention 1
  - docker run -d -p 5672:5672
     -h sorna-mq
     --name sorna-mq
     -e RABBITMQ_DEFAULT_USER=$SORNA_MQ_LOGIN
     -e RABBITMQ_DEFAULT_PASS=$SORNA_MQ_PASS
     -e RABBITMQ_DEFAULT_VHOST=$SORNA_NAMESPACE
     rabbitmq:3.6-alpine

script:
  - python -m pytest -m "not integration" --cov=sorna

after_success:
  - codecov
