language: python
python:
  - "3.6"
os:
  - linux
  # - osx  # not supported yet
install:
  - pip install -U pip
  - pip install -U wheel setuptools
  - pip install -U -r requirements-dev.txt
script:
  - python -m pytest -m "not integration" --cov=sorna
after_success:
  - codecov
