language: python
cache: pip
services:
  - docker

# stage decl.
stages:
  - name: test
  - name: deploy
    if: tag IS present

# build matrix for test stage
os:
  - linux
env:
  global:
    - BACKEND_ETCD_ADDR=localhost:2379
    - BACKEND_NAMESPACE=local
matrix:
  include:
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements-ci.txt
before_script:
  - mkdir -p /tmp/etcd
  - docker run -d -p 2379:2379 -p 2380:2380
     -v /tmp/etcd:/etcd-data
     --name backendai-etcd
     quay.io/coreos/etcd:v3.2.8
     /usr/local/bin/etcd
     --name backendai-etcd
     --data-dir /etcd-data
     --listen-client-urls http://0.0.0.0:2379
     --advertise-client-urls http://0.0.0.0:2379
     --listen-peer-urls http://0.0.0.0:2380
     --initial-advertise-peer-urls http://0.0.0.0:2380
     --initial-cluster backendai-etcd=http://0.0.0.0:2380
     --initial-cluster-token backendai-etcd-token
     --initial-cluster-state new
     --auto-compaction-retention 1
script:
  - python -m flake8 src tests
  - python -m pytest --cov=src
after_success:
  - codecov

# stage def.
jobs:
  include:
    - stage: deploy
      python: "3.6"
      install:
        - pip install -U pip setuptools
        - pip install -U -r requirements-build.txt
      before_script: skip
      script: skip
      after_success: skip
      deploy:
        on:
          tags: true
        provider: pypi
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        user: lablup
        password:
          secure: "rtjyTnqpkmG6FaL5Vr/4RTu5mhULx9Dp9V5YsQXgrxx4Q9ZcpnEVDWJDWtCSRoweVEKceuJ2e1vFp11rFpo9wfJiQiFrGlD66FxK6JH+ygKAsyDHoz4VbBqZXS15nibHIBzokxGKT3hpjrsdyXX+udu6CLm/CCliczUvS8yrXWPmuFl+Kt6wx7bblXTkpX35JM1AAACQtGkfiafEyUKQsaFSz9kuJ5TybF8fkEA9VBE0pIaS5wOe/ahl2siszS/XvVDrRkXs2A14ASGPdD1x0CFyE/NYFjg6fUzyL33k1f5f41xvVFHCao6FeELBmTc/SG1Uv4xK4k/nHW4e2cyidwxIl7wjYfYA/b93RVWpLl/0EPomL5Y8P41jXCwjKKqJTWCjG1TnGGVRGgXZC862ScCXiKUvQ6YX0tePGXsAY8vO/FqNKmyCE7bUuHK7ukKXXMjHZUaYAFe9iNgi16EePle0Uw6Fd8mmsxl51ifIWMvkYoufOtsDmP/H82SW6Ju4pbp+fdC6GYhJZvJrUY6uqzvD9tatQSxuRBrARjMTsnlh5DdqNxNMxkWrXEBcgdTeM02x/OK/QdeJ6yA2MYw15rQMxUJCW7G8pkEPdrz7UTxgoK5ZT2mGh21ALikQ+ZDleqfHz1kq9SGsD3XYRaWyPRpEtLwq09SOjLqYRfLvb2Q="

notifications:
  webhooks:
    secure: "Gd9njovK7f0UBDDuwwwNUSIhaipvQQOjXWkPsNXZr04eO43PqElnOn2emjDEiXO78Ovu5GGyUk27fhmqy7JdYTHPVAAd98fVbmzFwPu3XKvDNSrylbrckqoKRejcN5rRsPSzMFOklhwC/NHKiBz+XD2OhfITAqrnSc5BXKnHgBfPxK5s662oj6pQl3Uvvp5RCsuU8ceHq7xg224Kdkx2If+0oyB/8xRqG4E6vCS55jnxGFCOjGkfNg1wP8v9c8a9R7KNtz4ErlxQ5hVzCE8l6pHUTvscehzu/7JJmxziKLuXJYOyUGOKJCaHcYPRoUiPo6N0WbW1snDHK0d6XNGz7BFS3DVfzBama6pB3h4uiM02k8I+lm13L2xXN0A9ger0pRvDEieUTnXEc/zEy9wPCkSbFKMSkbshEPHnFzvDNJIaQELIQ+zXmNdBSCki3848WKMh85REwRwxczHr+bgz8JILb5DSgDBSJu2G7mOWCM5dohDrH6UfLI6fG4Dl48dJpu8pEO86PxE7MJ/u+fgnEGjINaaudoM29TQ4ArXNLHcC2C40ONWh/nsmzktAz/WgVPSvLtyJGA4lSgRkzxSGNr8rG1OMM1jeE/kBu246P26di+AcYX3o1JjKQhI3U2ql9ht0npIRWxO31aWn1kY+GYyjPt9/QSBTwPY0PY0dkxQ="
